-- TODO: Fix it
-- return {
--   cmd = { 'dockerls', '--stdio' },
--   filetypes = {
--     'html',
--     'blade',
--     'javascriptreact',
--     'typescriptreact',
--     'svelte',
--   },
--   root_markers = { 'index.html', '.git' },
--   init_options = { provideFormatter = true },
--   capabilities = vim.tbl_deep_extend('force', {}, vim.lsp.protocol.make_client_capabilities(), blink.get_lsp_capabilities()),
-- }
