import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-latte.toml"

  # "~/.config/alacritty/rose-pine.toml"
  # "~/.config/alacritty/rose-pine-moon.toml"
  # "~/.config/alacritty/rose-pine-dawn.toml"
  # "~/.config/alacritty/everforest.toml"
  # "~/.config/alacritty/gruvbox-dark.toml"
]
live_config_reload = true

[font]
size = 14
# builtin_box_drawing = true

[font.normal]
family = "JetBrainsMonoNL Nerd Font Propo"
style = "Medium"

# [font.normal]
# family = "Bitstream Vera Sans Mono"
# style = "Medium"


# [font.normal]
# family = "FiraCode Nerd Font Mono"
# style = "Retina"

# [font.normal]
# family = "Hack Nerd Font Mono"
# style = "Regular"

# [font.normal]
# family = "MonoLisa Nerd Font Mono"
# style = "Regular"


[font.bold]
family = "JetBrainsMonoNL Nerd Font Propo"
style = "Bold"

[font.italic]
family = "JetBrainsMonoNL Nerd Font Propo"
style = "Medium Italic"

[font.bold_italic]
family = "JetBrainsMonoNL Nerd Font Propo"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[window]
decorations = "Buttonless"
opacity = 0.95
blur = true

title = "Terminal"

[window.padding]
x = 15 
y = 15

[env]
TERM = "xterm-256color"
