background #1d2021
foreground #d4be98
selection_background #3c3836
selection_foreground #d4be98
url_color #7daea3
cursor #d8a657
cursor_text_color #1d2021
active_border_color #d8a657
inactive_border_color #504945
active_tab_foreground #d8a657
active_tab_background #282828
inactive_tab_foreground #928374
inactive_tab_background #3c3836
tab_bar_background #1d2021
color0 #32302f
color1 #ea6962
color2 #a9b665
color3 #d8a657
color4 #7daea3
color5 #d3869b
color6 #89b482
color7 #d4be98
color8 #928374
color9 #ea6962
color10 #a9b665
color11 #d8a657
color12 #7daea3
color13 #d3869b
color14 #89b482
color15 #ddc7a1
