# Minimal test config
format = """$directory$git_branch$character"""

[directory]
style = "bold #ff0000"
format = "[$path]($style) "

[git_branch]
style = "bold #0000ff"
format = "on [$symbol$branch]($style) "

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"