# Minimal test config
format = """$directory$git_branch$character"""

[directory]
style = "bold red"
format = "[$path]($style) "

[git_branch]
style = "bold blue"
format = "on [$symbol$branch]($style) "

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"