#
# # Get editor completions based on the config schema
# "$schema" = 'https://starship.rs/config-schema.json'
#
# palette = "kanagawa"
#
# format = """
# $directory \
# $git_branch \
# """
#
#
# # Inserts a blank line between shell prompts
# add_newline = true
#
# # Replace the '❯' symbol in the prompt with '➜'
# [character] # The name of the module we are configuring is 'character'
# success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
#
# [palettes.catppuccin_mocha]
# rosewater = "#f5e0dc"
# flamingo = "#f2cdcd"
# pink = "#f5c2e7"
# mauve = "#cba6f7"
# red = "#f38ba8"
# maroon = "#eba0ac"
# peach = "#fab387"
# yellow = "#f9e2af"
# green = "#a6e3a1"
# teal = "#94e2d5"
# sky = "#89dceb"
# sapphire = "#74c7ec"
# blue = "#89b4fa"
# lavender = "#b4befe"
# text = "#cdd6f4"
# subtext1 = "#bac2de"
# subtext0 = "#a6adc8"
# overlay2 = "#9399b2"
# overlay1 = "#7f849c"
# overlay0 = "#6c7086"
# surface2 = "#585b70"
# surface1 = "#45475a"
# surface0 = "#313244"
# base = "#1e1e2e"
# mantle = "#181825"
# crust = "#11111b"
#
# [aws]
# symbol = "  "
#
# [buf]
# symbol = " "
#
# [c]
# symbol = " "
#
# [conda]
# symbol = " "
#
# [crystal]
# symbol = " "
#
# [dart]
# symbol = " "
#
# [directory]
# read_only = " 󰌾"
#
# [docker_context]
# symbol = " "
#
# [elixir]
# symbol = " "
#
# [elm]
# symbol = " "
#
# [fennel]
# symbol = " "
#
# [fossil_branch]
# symbol = " "
#
# [git_branch]
# symbol = " "
#
# [golang]
# symbol = " "
#
# [guix_shell]
# symbol = " "
#
# [haskell]
# symbol = " "
#
# [haxe]
# symbol = " "
#
# [hg_branch]
# symbol = " "
#
# [hostname]
# ssh_symbol = " "
#
# [java]
# symbol = " "
#
# [julia]
# symbol = " "
#
# [kotlin]
# symbol = " "
#
# [lua]
# symbol = " "
#
# [memory_usage]
# symbol = "󰍛 "
#
# [meson]
# symbol = "󰔷 "
#
# [nim]
# symbol = "󰆥 "
#
# [nix_shell]
# symbol = " "
#
# [nodejs]
# symbol = " "
#
# [ocaml]
# symbol = " "
#
# [os.symbols]
# Alpaquita = " "
# Alpine = " "
# AlmaLinux = " "
# Amazon = " "
# Android = " "
# Arch = " "
# Artix = " "
# CentOS = " "
# Debian = " "
# DragonFly = " "
# Emscripten = " "
# EndeavourOS = " "
# Fedora = " "
# FreeBSD = " "
# Garuda = "󰛓 "
# Gentoo = " "
# HardenedBSD = "󰞌 "
# Illumos = "󰈸 "
# Kali = " "
# Linux = " "
# Mabox = " "
# Macos = " "
# Manjaro = " "
# Mariner = " "
# MidnightBSD = " "
# Mint = " "
# NetBSD = " "
# NixOS = " "
# OpenBSD = "󰈺 "
# openSUSE = " "
# OracleLinux = "󰌷 "
# Pop = " "
# Raspbian = " "
# Redhat = " "
# RedHatEnterprise = " "
# RockyLinux = " "
# Redox = "󰀘 "
# Solus = "󰠳 "
# SUSE = " "
# Ubuntu = " "
# Unknown = " "
# Void = " "
# Windows = "󰍲 "
#
# [package]
# symbol = "󰏗 "
#
# [perl]
# symbol = " "
#
# [php]
# symbol = " "
# style = "bold #957FB8"
#
# [pijul_channel]
# symbol = " "
#
# [python]
# symbol = " "
#
# [rlang]
# symbol = "󰟔 "
#
# [ruby]
# symbol = " "
#
# [rust]
# symbol = "󱘗 "
#
# [scala]
# symbol = " "
#
# [swift]
# symbol = " "
#
# [zig]
# symbol = " "


command_timeout = 1000

"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false 

format = """
 ➜\
$directory\
${custom.giturl}\
$git_branch
"""

right_format = """$all"""

# palette = "kanagawa"

[palettes.kanagawa]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'
# Add missing colors that your config uses - using brighter kanagawa colors
sapphire = "#7fb4ca"  # bright blue from kanagawa
lavender = "#d27e99"  # bright pink/magenta from kanagawa  
black = "#16161d"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

# [palettes.custom]
# rosewater = "#f5e0dc"
# flamingo = "#eb6f92"
# pink = "#f5c2e7"
# orange = "#cba6f7"
# color_red = '#cc241d'
# red = "#f38ba8"
# maroon = "#eba0ac"
# peach = "#fab387"
# yellow = "#f9e2af"
# green = "#a6e3a1"
# teal = "#94e2d5"
# sky = "#89dceb"
# sapphire = "#74c7ec"
# blue = "#89b4fa"
# lavender = "#b4befe"
# foam = "#9ccfd8"
# pine = "#31748f"
# gold = "#f6c177"
# rose = "#ebbcba"
# text = "#cdd6f4"
# subtext1 = "#bac2de"
# subtext0 = "#a6adc8"
# overlay2 = "#9399b2"
# overlay1 = "#7f849c"
# overlay0 = "#6c7086"
# surface2 = "#585b70"
# surface1 = "#45475a"
# surface0 = "#313244"
# base = "#1e1e2e"
# mantle = "#181825"
# crust = "#11111b"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = " "
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
#show_always = true
#style_user = "bg:surface0 fg:text"
#style_root = "bg:surface0 fg:text"
#format = '[ $user ]($style)'

[directory]
style = "blue"
format = "[ $path ]($style)"
#truncation_length = 4
#truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[os]
disabled = true
#style = "bg:surface0 fg:text"

[custom.giturl]
# disabled = true
description = "Display symbol for remote Git server"
command = """
GIT_REMOTE=$(command git ls-remote --get-url 2> /dev/null)
if [[ "$GIT_REMOTE" =~ "github" ]]; then
    GIT_REMOTE_SYMBOL=" "
elif [[ "$GIT_REMOTE" =~ "gitlab" ]]; then
    GIT_REMOTE_SYMBOL=" "
elif [[ "$GIT_REMOTE" =~ "bitbucket" ]]; then
    GIT_REMOTE_SYMBOL=" "
elif [[ "$GIT_REMOTE" =~ "git" ]]; then
    GIT_REMOTE_SYMBOL=" "
else
    GIT_REMOTE_SYMBOL=" "
fi
echo "$GIT_REMOTE_SYMBOL "
"""
when = 'git rev-parse --is-inside-work-tree 2> /dev/null'
format = "at $output"

[git_branch]
symbol = " "
# format =  ' [$symbol$branch(:$remote_branch)]($style)[]'
style = "green"
format = "  on [$symbol$branch]($style)"

[git_status]
format = ' [($all_status$ahead_behind )]($style)'

[nodejs]
symbol = ""
format = '[ $symbol( $version) ]($style)'

[c]
symbol = " "
format = '[[ $symbol( $version) ]]($style)'

[rust]
symbol = ""
format = '[[ $symbol( $version) ]]($style)'

[golang]
symbol = ""
format = '[ $symbol( $version) ]($style)'
detect_files = ["go.mod"]

[java]
symbol = " "
format = '[[ $symbol( $version) ]]($style)'

[kotlin]
symbol = ""

format = '[[ $symbol( $version) ]]($style)'

[haskell]
symbol = ""

format = '[[ $symbol( $version) ]]($style)'

[python]
symbol = ""

format = '[[ $symbol( $version) ]]($style)'


[docker_context]
symbol = ""
format = '[ $symbol( $context) ]($style)'


[time]
disabled = false
time_format = "%R"
style = "bg:peach"
format = '[[  $time ](fg:mantle bg:foam)]($style)'

[line_break]
disabled = true 

[character]
disabled = false
success_symbol = '[𝘹](bold fg:green)'
error_symbol = '[𝘹](bold fg:red)'
vimcmd_symbol = '[](bold fg:creen)'
vimcmd_replace_one_symbol = '[](bold fg:purple)'
vimcmd_replace_symbol = '[](bold fg:purple)'
vimcmd_visual_symbol = '[](bold fg:lavender)'
