-- Neovim configuration entrypoint. Each concern lives in lua/config/.
require('config.options')
require('config.plugins')
require('config.keymaps')
require('config.plugin_setup')
require('config.autocmds')
require('config.ui_lsp')
require('config.statusline')
require('config.commands')
require('config.colors')
