-- Generated by nwg-displays on 2026-07-27 at 09:02:59. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@60.0",
    position = "4327x540",
    scale = 1.2,
    bitdepth = 10
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@60.0",
    position = "1767x0",
    scale = 1.0
})
