-- Generated by nwg-displays on 2026-08-21 at 10:28:49. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@60.0",
    position = "3696x360",
    scale = 1.0,
    bitdepth = 10
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@60.0",
    position = "1776x360",
    scale = 1.0
})
