-- Generated by nwg-displays on 2026-07-23 at 11:47:13. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@60.0",
    position = "1767x1080",
    scale = 1.0,
    bitdepth = 10
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@74.97",
    position = "1600x0",
    scale = 1.0
})
