gui:
  theme:
    activeBorderColor:
      - '#698a9b'
    inactiveBorderColor:
      - '#2A2A37'
    optionsTextColor:
      - '#c4b28a'
    selectedLineBgColor:
      - '#363646'
    defaultFgColor:
      - '#DCD7BA'
