lastupdatecheck: 0
recentrepos:
- /Users/kamil/.dotfiles
- /Users/kamil/Work/Projects/wamt-crm
startuppopupversion: 5
customcommandshistory: []
hidecommandlog: false
ignorewhitespaceindiffview: false
