lastupdatecheck: 0
recentrepos:
- /Users/kamil/.dotfiles
- /Users/kamil/Work/Projects/perfexim/infra
- /Users/kamil/Work/Projects/wamt-crm
- /Users/kamil/Work/Projects/bodzio/front
startuppopupversion: 5
customcommandshistory: []
hidecommandlog: false
ignorewhitespaceindiffview: false
