# Live-editable aliases shared by macOS and NixOS.
alias n='nvim .'
alias y='yazi .'
alias x='exit'
alias o='omp'
alias or='omp --resume'
alias oc='opencode'
alias lg='lazygit'
alias ldk='lazydocker'
alias ls='eza --no-filesize --long --color=always --icons=always --no-user'
alias lt='eza --git --color=always --icons --tree'
alias grep='grep --color=auto'
alias reset_zsh='source ~/.zshrc'
alias clear_nvim_cache='rm -rf ~/.local/share/nvim'
alias jira='~/bin/jira'
alias serpl='~/bin/serpl'
alias doom='~/.config/emacs/bin/doom'
alias private_gitignore='nvim .git/info/exclude'
alias git_log='serie'
alias spf='command superfile --config-file ~/.config/superfile/config.toml --hotkey-file ~/.config/superfile/hotkeys.toml'
alias slk='env -u WAYLAND_DISPLAY command slk'
alias superfile='command superfile --config-file ~/.config/superfile/config.toml --hotkey-file ~/.config/superfile/hotkeys.toml'
alias gpod='git pull origin development'
alias gc='git checkout'
alias gcb='git checkout -b'
alias gags='git add . && git stash'
alias gsp='git stash pop'
alias wgs='sudo wg show'
alias wgr='sudo systemctl restart wg-quick-wg0.service'
