name: Nix evaluation

on:
  pull_request:
  push:
    branches: [master, main]

jobs:
  flake-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v22
        with:
          determinate: false
      - name: Evaluate macOS and NixOS outputs
        run: |
          nix eval --raw ./nix#nixosConfigurations.nixos.config.system.build.toplevel.drvPath
          nix eval --raw ./nix#darwinConfigurations.MacBook-Pro-Kamil.system.drvPath
